# Generated by Django 3.2.6 on 2021-08-30 16:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('dealer_id', models.IntegerField(null=True)),
                ('type', models.CharField(choices=[('S', 'Sedan'), ('U', 'SUV'), ('W', 'Wagon'), ('M', 'Muscle')], max_length=1)),
                ('year', models.DateField(default=django.utils.timezone.now)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.carmake')),
            ],
        ),
    ]
